name: cypress-matrix

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [electron, chrome]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Cypress
        run: |
          npx cypress run --browser ${{ matrix.browser }} --headless             --reporter junit --reporter-options "mochaFile=results/junit-[hash].xml,toConsole=true"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.browser }}
          path: |
            results
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore
